<?php

namespace App\Models;

class ApiResponse
{
	public $Method;
	public $Param;
	public $Message;
	public $Update = array();
    public $Type;
	public $Data;
	public $Sync = array();	

	
	public function Sync($resp)
	{ 
		$this->Sync['QueryResponseRecords'] = $resp['query']['count'];
		$this->Sync['UpdatedRecords'] = $resp['query']['update'];
		$this->Sync['CreatedRecords'] = $resp['query']['create'];
		$this->Sync['QBconflict'] = $resp['query']['QBconflict'];
		$this->Sync['BCconflict'] = $resp['query']['BCconflict'];

		$this->Sync['BatchItemRequestRecords'] = $resp['requestCount'];
		$this->Sync['BatchItemResponseValidRecords'] = $resp['responseCount']['valid'];
		$this->Sync['BatchItemResponseFaultRecords'] = $resp['responseCount']['fault'];
	
		//the BatchItemResponse object is returned to the client QBs output screen since it is generated by QBs
		$this->Sync['Data'] = $resp['requestObj']; 
	}

	public function pretty_response()
	{
		return json_encode($this, JSON_PRETTY_PRINT);
	}  	
	
	public function EchoJson(){return json_encode($this);}
}
